update DNSEndpoint CRD url (#84)
External DNS changed the URL where they keep the DNSEndpoint CRD, which broke our pipeline:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/heads/master/charts/external-dns/crds/dnsendpoint.yaml
error: unable to read URL "https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/heads/master/charts/external-dns/crds/dnsendpoint.yaml", server reported 404 Not Found, status code=404
```

Signed-off-by: Andre Aguas <andre.aguas@protonmail.com>